import { ClerkProvider } from "@clerk/nextjs/app-beta";
import { dark } from "@clerk/themes";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import type { ReactNode } from "react";

import { Toaster } from "@/components/config";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// TODO: Update description
export const metadata: Metadata = {
  title: "OnlyHabits | Building better habits for a better you",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`bg-base-300 text-base-content ${inter.className}`}>
        <ClerkProvider appearance={{ baseTheme: dark }}>
          {children}
        </ClerkProvider>

        <Toaster />
      </body>
    </html>
  );
}
